apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  # this setting is to make sure the source IP address is preserved.
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 80