---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki
  namespace: logging
  labels:
    app: loki
rules:
- apiGroups: ['extensions']
  resources:
  - pods
  - namespaces
  verbs: ['use']
  resourceNames: [loki]