apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: monitoring
spec:
  storageClassName: monitoring-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: monitoring
spec:
  storageClassName: monitoring-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

