apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob2
spec:
  schedule: "*/1 * * * *"
  # concurrencyPolicy has three possible values - Forbid, Allow and Replace
  # Since the schedule is every one min and the container runs for 90 seconds, 
  # you will see multiple Jobs running at the same time. 
  # This overlap is possible since we have applied concurrencyPolicy: Allow
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo sleeping....; sleep 90s; echo exiting...;
          restartPolicy: Never
