apiVersion: v1
kind: PersistentVolume
metadata:
  name: stan-volume-0
spec:
  capacity:
    storage: 16Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: stan-storage
  local:
    path: /data/stan-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - luffy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stan-volume-1
spec:
  capacity:
    storage: 16Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: stan-storage
  local:
    path: /data/stan-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - luffy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stan-volume-2
spec:
  capacity:
    storage: 16Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: stan-storage
  local:
    path: /data/stan-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - luffy