---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-vol
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rabbitmq-storage
  local:
    path: /data/rabbitmq
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - miwa
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-vol-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rabbitmq-storage
  local:
    path: /data/rabbitmq-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - miwa
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-vol-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rabbitmq-storage
  local:
    path: /data/rabbitmq-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - miwa