apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-vol-0
  labels:
    storage-tier: es-logging
spec:
  capacity:
    storage: 3Gi
  # volumeMode: Filesystem # can be set to "Block" (instead of the default value "Filesystem") 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/es
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - morris
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-vol-1
  labels:
    storage-tier: es-logging
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/es
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - luffy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-vol-2
  labels:
    storage-tier: es-logging
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/es
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - miwa
