---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter-svc
  labels:
    app: kafka-exporter
  annotations:
    prometheus.io/port: metrics
    prometheus.io/scrape: "true"
spec:
  selector:
    app: kafka-exporter
  ports:
  - port: 9308
    name: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
      annotations:
        prometheus.io/port: metrics
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9308
          name: metrics
        command:
        - kafka_exporter
        - --kafka.server=kafka-0.kafka-hs.default.svc.cluster.local:9092
        - --kafka.server=kafka-1.kafka-hs.default.svc.cluster.local:9092
        - --kafka.server=kafka-2.kafka-hs.default.svc.cluster.local:9092
        - --kafka.version=2.6.1
        - --web.listen-address=:9308
        - --log.level=info
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "250m"